-- DO NOT EDIT THIS FILE! --
-- This file stores variables for hyprland to read.
-- Any changes made to this file will either break 
-- everything or be overwritten after a restart
require("lilac")
hl_terminal = ""
hl_fileManager = ""
hl_menu = ""
ll_gameMode = "0"
ll_username = ""
basePath = "" -- path to the hyprland config folder. Calculated at lilac::lua::startLilac()
hl_isLaptop = false
hl_desktopSwitchSpeed = 0
setupComplete = false;
