#include <iostream>
#include <fstream>
#include <string>

using namespace std;
string basePath = "";
string inPath = "gamingMonitors.lua";
string outPath = "internal/monitors.lua";
string defaultPath = "monitors.lua";

inline int toInt(std::string s)
{
  return stoi(s);
}

inline void notify(string n)
{
  system(string("notify-send \"" + n + "\" -a 'lilac::gamingMode()'").c_str());
}

inline void error(string e)
{
  notify("[FATAL]: " + e);
  cerr << e << '\n';
}

int main(int argc, char *argv[])
{
  if (argc < 2)
  {
    error("Requires at least 2 arguments");
    exit(1);
  }

  if (argc > 3)
  {
    error("Too many arguments");
    exit(1);
  }
  basePath = argv[1];
  inPath =  basePath + inPath;
  outPath = basePath + outPath;
  defaultPath = basePath + defaultPath;

  string lineIn;
  unsigned int oldFileSize = 0;
  string p = inPath;
  bool restore = toInt(argv[2]);
  if (restore)
    p = defaultPath;

  ifstream inFile(p);
  ofstream outFile(outPath);
  if (!inFile.is_open())
  {
    error("Failed to open file: " + p);
    inFile.close();
    exit(1);
  }
  if (!outFile.is_open())
  {
    error("Failed to open file: " + outPath);
    outFile.close();
    exit(1);
  }

  outFile << "-- DO NOT EDIT THIS FILE! --\n--This file was generated by lilac::gamingMode() to apply monitor settings!\n-- The file you are looking for is ~/.config/hypr/monitors.lua\n\n";

  while (getline(inFile, lineIn))
  {
    outFile << lineIn << std::endl;
  }

  inFile.close();
  outFile.close();
  return 0;
}
