general {
    on_lock_cmd = bash -c "~/.config/hypr/lilac/lilacPM/lockState /home/$(whoami)/.config/hypr/ 1"
    on_unlock_cmd = bash -c "~/.config/hypr/lilac/lilacPM/lockState /home/$(whoami)/.config/hypr/ 0"
    lock_cmd = bash -c "~/.config/hypr/lilac/lilacPM/lockState /home/$(whoami)/.config/hypr/ 1"
    unlock_cmd = bash -c "~/.config/hypr/lilac/lilacPM/lockState /home/$(whoami)/.config/hypr/ 0"
}
